run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck

linters-settings:
  errcheck:
    # Ignore specific functions where error checking is often skipped
    exclude-functions:
      - fmt.Fprintf
      - fmt.Printf
      - fmt.Print

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 10
