version: 2

project_name: monkey

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: monkey
    main: ./main.go
    binary: monkey
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X monkey/cmd.Version={{.Version}}
      - -X monkey/cmd.Commit={{.Commit}}
      - -X monkey/cmd.Date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: alex-popov-tech
    name: go-interpreter
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
